name := "NSPL_Recon"
version := "1.0"
scalaVersion := "2.11.11"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.2.0"
libraryDependencies += "org.apache.spark" %% "spark-core" % "2.2.0"
libraryDependencies += "mysql" % "mysql-connector-java" % "5.1.45"
libraryDependencies += "com.datastax.cassandra" % "cassandra-driver-core" % "1.0.5-dse"
